"use client";
import { AlertTriangle, Bell, CheckCircle2, MailCheck } from "lucide-react";
import { useCallback, useEffect, useState } from "react";
import type { MaintenanceAlert, MaintenanceAlertResponse } from "@/types/maintenance-alert";

const empty:MaintenanceAlertResponse={data:[],allMaintenance:[],summary:{total:0,approaching:0,overdue:0}};
export function MaintenanceAlerts(){const [result,setResult]=useState(empty),[loading,setLoading]=useState(true);const load=useCallback(async()=>{setLoading(true);try{const r=await fetch("/api/maintenance-alerts");if(r.ok){const data=await r.json();setResult({...data,data:data.data??[],allMaintenance:data.allMaintenance??data.data??[]});}}finally{setLoading(false);}},[]);useEffect(()=>{const t=setTimeout(()=>void load(),0);return()=>clearTimeout(t);},[load]);return <div className="inventory-view alert-view"><header className="page-header"><div><span className="eyebrow">Filo yönetimi</span><h1>Bakım Planı</h1><p>Yaklaşan ve planlanan tüm bakımları kilometre sırasıyla takip edin.</p></div><span className="automatic-mail-note"><MailCheck/>Uyarılar yönetici e-postasına otomatik gönderilir</span></header>
 <section className="alert-summary"><article><span className="alert-stat-icon"><Bell/></span><div><small>Kritik uyarı</small><strong>{result.summary.total}</strong></div></article><article className="warm"><span className="alert-stat-icon"><AlertTriangle/></span><div><small>Yaklaşıyor</small><strong>{result.summary.approaching}</strong></div></article><article className="danger"><span className="alert-stat-icon"><AlertTriangle/></span><div><small>Gecikmiş</small><strong>{result.summary.overdue}</strong></div></article></section>
 <section className="inventory-panel maintenance-section"><div className="inventory-title-row"><div><h2>En yakın bakım uyarıları</h2><p>Bakım kilometresi yaklaşan veya geçen araçlar</p></div><span>{loading?"Yükleniyor…":`${result.data.length} araç`}</span></div>{result.data.length?<div className="alert-list">{result.data.map((a)=><MaintenanceRow alert={a} key={a.vehicleId} critical/>)}</div>:<div className="dashboard-all-clear"><CheckCircle2/><span><b>Kritik bakım uyarısı yok</b><small>Yaklaşan veya geciken bir araç bulunmuyor.</small></span></div>}</section>
 <section className="inventory-panel maintenance-section all-plan"><div className="inventory-title-row"><div><h2>Tüm bakım zamanları</h2><p>En yakın bakım kilometresinden en uzağa doğru sıralı</p></div><span>{result.allMaintenance.length} plan</span></div>{result.allMaintenance.length?<div className="alert-list">{result.allMaintenance.map((a,index)=><MaintenanceRow alert={a} key={a.vehicleId} order={index+1}/>)}</div>:<div className="empty-state"><span><Bell/></span><h3>Planlanmış bakım yok</h3><p>Araç envanterinden sonraki bakım kilometresini ekleyebilirsiniz.</p></div>}</section></div>}
function MaintenanceRow({alert,critical=false,order}:{alert:MaintenanceAlert;critical?:boolean;order?:number}){return <article className={`alert-card ${alert.status.toLowerCase()}`}><span className="maintenance-order">{critical?<AlertTriangle/>:order}</span><div className="alert-main"><div><strong>{alert.plate}</strong><span>{alert.brand} {alert.model}</span></div><p>{alert.company.name} · {alert.unit.name}</p></div><div className={`dashboard-alert-state ${alert.status.toLowerCase()}`}><b>{alert.remainingMileage<0?"Gecikti":alert.remainingMileage===0?"Bakım zamanı":"Planlandı"}</b><small>{alert.remainingMileage<0?`${Math.abs(alert.remainingMileage).toLocaleString("tr-TR")} km geçti`:`${alert.remainingMileage.toLocaleString("tr-TR")} km kaldı`} · Hedef {alert.nextMaintenanceMileage.toLocaleString("tr-TR")} km</small></div></article>}
