"use client";
import { CalendarRange, CarFront, CheckCircle2, Download, FileSpreadsheet, Wrench } from "lucide-react";
import { useEffect, useState } from "react";
import type { Company } from "@/types/vehicle";

export function Reports(){
  const [companies,setCompanies]=useState<Company[]>([]);const [companyId,setCompanyId]=useState("");const [dateFrom,setDateFrom]=useState("");const [dateTo,setDateTo]=useState("");const [downloading,setDownloading]=useState(false);const [error,setError]=useState("");const [success,setSuccess]=useState(false);
  useEffect(()=>{void fetch("/api/companies").then((r)=>r.json()).then(setCompanies);},[]);
  async function download(){setDownloading(true);setError("");setSuccess(false);try{const query=new URLSearchParams();if(companyId)query.set("companyId",companyId);if(dateFrom)query.set("dateFrom",dateFrom);if(dateTo)query.set("dateTo",dateTo);const response=await fetch(`/api/reports/excel?${query}`);if(!response.ok){const body=await response.json();throw new Error(body.message??"Rapor oluşturulamadı.");}const blob=await response.blob();const url=URL.createObjectURL(blob);const link=document.createElement("a");link.href=url;link.download=`filo-raporu-${new Date().toISOString().slice(0,10)}.xlsx`;document.body.appendChild(link);link.click();link.remove();URL.revokeObjectURL(url);setSuccess(true);}catch(e){setError(e instanceof Error?e.message:"Rapor indirilemedi.");}finally{setDownloading(false);}}
  return <div className="inventory-view reports-view"><header className="page-header"><div><span className="eyebrow">Filo yönetimi</span><h1>Raporlar</h1><p>Araç ve bakım kayıtlarını Excel dosyası olarak arşivleyin.</p></div></header>
    <div className="report-layout"><section className="report-builder"><header><span><FileSpreadsheet/></span><div><h2>Excel Raporu Oluştur</h2><p>Seçtiğiniz filtrelere göre düzenli ve kullanıma hazır bir çalışma kitabı hazırlanır.</p></div></header>
      <div className="report-content"><div className="report-includes"><h3>Raporda neler olacak?</h3><article><span><CarFront/></span><div><b>Araç Envanteri</b><p>Araç bilgileri, şirket, kullanan birim, HGS ve bakım kilometreleri</p></div></article><article><span><Wrench/></span><div><b>Bakım ve Tamir</b><p>Yapılan işlemler, değişen parçalar, servis ve toplam maliyetler</p></div></article><article><span><FileSpreadsheet/></span><div><b>Özet Sayfası</b><p>Toplam araç, bakım, tamir ve maliyet rakamları</p></div></article></div>
        <div className="report-filters"><h3>Rapor filtreleri</h3><label><span>Şirket</span><select value={companyId} onChange={(e)=>setCompanyId(e.target.value)}><option value="">Tüm şirketler</option>{companies.map((c)=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><div className="date-pair"><label><span>Başlangıç tarihi</span><input type="date" value={dateFrom} onChange={(e)=>setDateFrom(e.target.value)}/></label><label><span>Bitiş tarihi</span><input type="date" value={dateTo} onChange={(e)=>setDateTo(e.target.value)}/></label></div><p className="report-hint"><CalendarRange/>Tarih filtresi bakım ve tamir kayıtlarına uygulanır. Araç envanteri güncel haliyle eklenir.</p>{success?<p className="settings-success"><CheckCircle2/>Excel raporu başarıyla indirildi.</p>:null}{error?<p className="form-error">{error}</p>:null}<button className="primary-action report-download" disabled={downloading} onClick={download}><Download/>{downloading?"Rapor hazırlanıyor…":"Excel Raporunu İndir"}</button></div>
      </div></section></div></div>;
}
