"use client";
import { Building2, ChevronRight, Pencil, Plus, Save, UsersRound, X } from "lucide-react";
import { FormEvent, useCallback, useEffect, useState } from "react";
import type { Company, Unit } from "@/types/vehicle";

export function OrganizationManagement(){
 const [companies,setCompanies]=useState<Company[]>([]),[selected,setSelected]=useState(""),[units,setUnits]=useState<Unit[]>([]);const [modal,setModal]=useState<"company"|"unit"|null>(null);const [editing,setEditing]=useState<{kind:"company"|"unit";id:string;name:string}|null>(null);
 const loadCompanies=useCallback(async()=>{const r=await fetch("/api/companies");if(r.ok){const data:Company[]=await r.json();setCompanies(data);setSelected((v)=>v||data[0]?.id||"");}},[]);
 useEffect(()=>{const t=setTimeout(()=>void loadCompanies(),0);return()=>clearTimeout(t);},[loadCompanies]);
 const loadUnits=useCallback(async()=>{if(!selected)return setUnits([]);const r=await fetch(`/api/companies/${selected}/units`);if(r.ok)setUnits(await r.json());},[selected]);
 useEffect(()=>{const t=setTimeout(()=>void loadUnits(),0);return()=>clearTimeout(t);},[loadUnits]);
 const company=companies.find((c)=>c.id===selected);
 async function save(kind:"company"|"unit",name:string,id?:string){const url=id?(kind==="company"?`/api/companies/${id}`:`/api/units/${id}`):(kind==="company"?"/api/companies":`/api/companies/${selected}/units`);const r=await fetch(url,{method:id?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name})});if(!r.ok){const b=await r.json();throw new Error(Array.isArray(b.message)?b.message.join(" "):b.message);}await loadCompanies();await loadUnits();}
 return <div className="inventory-view organization-view"><header className="page-header"><div><span className="eyebrow">Filo yönetimi</span><h1>Şirket ve Birimler</h1><p>Şirket yapısını ve araçları kullanan birimleri yönetin.</p></div><button className="primary-action" onClick={()=>setModal("company")}><Plus/>Yeni Şirket</button></header><div className="organization-layout"><section className="company-panel"><header><div><h2>Şirketler</h2><p>{companies.length} şirket kayıtlı</p></div></header><div className="company-list">{companies.map((c)=><button className={selected===c.id?"active":""} key={c.id} onClick={()=>setSelected(c.id)}><span><Building2/></span><div><b>{c.name}</b><small>Şirket kaydı</small></div><ChevronRight/></button>)}</div></section><section className="unit-panel"><header><div><span className="unit-company-icon"><Building2/></span><div><h2>{company?.name??"Şirket seçiniz"}</h2><p>{units.length} birim bağlı</p></div></div><div className="unit-actions">{company?<button className="icon-action" onClick={()=>setEditing({kind:"company",id:company.id,name:company.name})}><Pencil/></button>:null}<button className="primary-action" disabled={!selected} onClick={()=>setModal("unit")}><Plus/>Yeni Birim</button></div></header>{units.length?<div className="unit-grid">{units.map((u)=><article key={u.id}><span><UsersRound/></span><div><b>{u.name}</b><small>Aracı kullanan birim</small></div><button onClick={()=>setEditing({kind:"unit",id:u.id,name:u.name})}><Pencil/></button></article>)}</div>:<div className="empty-state"><span><UsersRound/></span><h3>Henüz birim yok</h3><p>Bu şirkete ilk birimi ekleyebilirsiniz.</p></div>}</section></div>{modal?<NameModal title={modal==="company"?"Yeni Şirket":"Yeni Birim"} onClose={()=>setModal(null)} onSave={async(name)=>{await save(modal,name);setModal(null);}}/>:null}{editing?<NameModal title={editing.kind==="company"?"Şirketi Düzenle":"Birimi Düzenle"} initial={editing.name} onClose={()=>setEditing(null)} onSave={async(name)=>{await save(editing.kind,name,editing.id);setEditing(null);}}/>:null}</div>;
}
function NameModal({title,initial="",onClose,onSave}:{title:string;initial?:string;onClose:()=>void;onSave:(name:string)=>Promise<void>}){const [name,setName]=useState(initial),[saving,setSaving]=useState(false),[error,setError]=useState("");async function submit(e:FormEvent){e.preventDefault();setSaving(true);try{await onSave(name.trim());}catch(err){setError(err instanceof Error?err.message:"İşlem tamamlanamadı.");}finally{setSaving(false);}}return <div className="modal-backdrop"><section className="name-modal"><header><div><span className="eyebrow">Organizasyon</span><h2>{title}</h2></div><button onClick={onClose}><X/></button></header><form onSubmit={submit}><label><span>Ad</span><input autoFocus required minLength={2} maxLength={120} value={name} onChange={(e)=>setName(e.target.value)}/></label>{error?<p className="form-error">{error}</p>:null}<footer><button type="button" className="secondary-action" onClick={onClose}>Vazgeç</button><button className="primary-action" disabled={saving}><Save/>{saving?"Kaydediliyor…":"Kaydet"}</button></footer></form></section></div>}
